### PR TITLE
abstracted image storage

### PR DESCRIPTION
**Pull request by brian030128**

### CODE REVIEW

**Review by brian030128 — COMMENTED** [review]
good

**Comment by brian030128** [comment]
@GNITOAHC  欸我好像沒辦法自己review然後過pull request

**Review by GNITOAHC — APPROVED** [review]

**Comment by GNITOAHC** [comment]
@SpeedReach 應該可以了

**Comment by brian030128** [comment]
@GNITOAHC  他好像說我沒write access 沒辦法merge

**Pull request merged**
